# Generated by Django 2.2.28 on 2023-07-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nbddh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcsvsv', models.BigIntegerField()),
                ('ieyuey', models.BigIntegerField()),
            ],
        ),
    ]
